version: "3.8"
services:
  web:
    image: a1d4r/flask-model-evaluation:register
    ports:
      - "5000:5000"
    environment: 
      - FLASK_APP=main.py 
      - FLASK_ENV=development
      - ROUTING_SERVER_URL=18.216.27.126:8080
    volumes:
      - ./app:/app
    entrypoint: flask run --host=0.0.0.0 --port=5000